version: '3.8'
services:
  proxy-checker-react:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    container_name: proxy-checker-react
    volumes:
       - ./:/usr/src/app
       - /usr/src/app/node_modules